#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

mkdir -p "$PLUSHU_ROOT/nginx/main"
mkdir -p "$PLUSHU_ROOT/nginx/events"
mkdir -p "$PLUSHU_ROOT/nginx/http"
mkdir -p "$PLUSHU_ROOT/nginx/mail"
mkdir -p "$PLUSHU_ROOT/ssl"

# If there's no pre-existing nginx.conf
if [[ ! -f "$PLUSHU_ROOT/nginx/nginx.conf" ]]; then
  # Make a basic conf that reads from directories
  cat > "$PLUSHU_ROOT/nginx/nginx.conf" <<EOF
include main/*.conf;
events { include events/*.conf; }
http { include http/*.conf; }
mail { include mail/*.conf; }
EOF
fi

# Make sure we disable daemonization - docker wants nginx in the foreground
if [[ ! -f "$PLUSHU_ROOT/nginx/main/daemon-off.conf" ]]; then
  cat > "$PLUSHU_ROOT/nginx/main/daemon-off.conf" <<EOF
daemon off;
EOF
fi

if [[ "$EUID" == 0 ]]; then
  chown -R plushu "$PLUSHU_ROOT/nginx"
  chown -R plushu "$PLUSHU_ROOT/ssl"
fi

docker pull nginx
docker run --name plushu-nginx --net=host \
  -v "$PLUSHU_ROOT/nginx:/usr/local/nginx/etc" \
  -v "$PLUSHU_ROOT/ssl:/usr/local/nginx/etc/ssl" \
  -d --entrypoint=nginx nginx -c /usr/local/nginx/etc/nginx.conf >/dev/null
